# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MindGarden' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MindGarden
   pod 'Firebase/Auth'
   pod 'Firebase/Firestore'
   pod 'Firebase/Analytics'
   pod 'FirebaseUI'

  target 'MindGardenTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MindGardenUITests' do
    # Pods for testing
  end

end
